### ISSUE TITLE
PandaPush, PandaStack, assign @CUN-bjy

### ISSUE THREAD

**Issue by CUN-bjy** [ropiens/project-sandwich-man#5]

**Comment by CUN-bjy** [comment]
### PandaPush-v1
![Screenshot from 2021-08-24 10-58-22](https://user-images.githubusercontent.com/26274945/130543675-d940f8d0-2e49-48c9-8ace-f49398359303.png)
![Peek 2021-08-24 10-59](https://user-images.githubusercontent.com/26274945/130543697-90dc0fa6-5f75-47b8-9b65-9edb6c5612af.gif)

**Comment by benthebear93** [comment]
### PandaStack-v1
![PandaStack_log](https://user-images.githubusercontent.com/34788458/130616237-7e37422d-1e31-43a5-820b-151535b559aa.PNG)
![PandaStack](https://user-images.githubusercontent.com/34788458/130616221-c60e3214-760c-417b-b035-af85c378f767.gif)

**Comment by CUN-bjy** [comment]
It seems impossible to learn a single-step stacking task with a sparse reward(e.g. PandaStack).
We need to apply the multi-step(hierarchical) structure!
